vcl,xmloff,svgio,oox,sd: missing stdint.h
error: ‘uint64_t’ does not name a type

Change-Id: I732484842f694ea9b0f7ec379609d29a92ef5a87
Reviewed-on: https://gerrit.collaboraoffice.com/c/core/+/7459
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>
Tested-by: Michael Stahl <michael.stahl@collabora.com>