-Werror=maybe-uninitialized in sfx2
/home/julien/lo/libo_perf/sfx2/source/dialog/splitwin.cxx: In member function ‘void SfxSplitWindow::InsertWindow(SfxDockingWindow*, const Size&)’:
/home/julien/lo/libo_perf/sfx2/source/dialog/splitwin.cxx:462:23: error: ‘nL’ may be used uninitialized [-Werror=maybe-uninitialized]
  462 |                 nLine = static_cast<short>(nL);
      |                 ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
/home/julien/lo/libo_perf/sfx2/source/dialog/splitwin.cxx:433:16: note: ‘nL’ was declared here
  433 |     sal_uInt16 nL;
      |                ^~
/home/julien/lo/libo_perf/sfx2/source/dialog/splitwin.cxx: In member function ‘void SfxSplitWindow::MoveWindow(SfxDockingWindow*, const Size&, sal_uInt16, sal_uInt16, bool)’:
/home/julien/lo/libo_perf/sfx2/source/dialog/splitwin.cxx:552:21: error: ‘nL’ may be used uninitialized [-Werror=maybe-uninitialized]
  552 |     if ( nLine > nL && GetItemCount( GetItemId( nL ) ) == 1 )
      |          ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/julien/lo/libo_perf/sfx2/source/dialog/splitwin.cxx:548:16: note: ‘nL’ was declared here
  548 |     sal_uInt16 nL, nP;
      |                ^~

Change-Id: I816ec49fe2c63e4f448ae83251d3a24b08383903
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/172306
Reviewed-by: Julien Nabet <serval2412@yahoo.fr>
Tested-by: Jenkins
(cherry picked from commit 73884e28faeb457c01b80051a701c073112ad564)
(cherry picked from commit 6348e98173f0f4a361e893cb272f44c902bd86ee)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/191786
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>