comphelper: fix error: ‘PATH_MAX’ was not declared in this scope
Change-Id: I6092ae990e7e26cfcc073f951fb3a1bdf75a191a
Reviewed-on: https://gerrit.collaboraoffice.com/c/core/+/5952
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>
Tested-by: Michael Stahl <michael.stahl@collabora.com>
(cherry picked from commit d355cdcb67c5248a2cab212912a1d934d14d52fe)
Reviewed-on: https://gerrit.collaboraoffice.com/c/core/+/7445